apiVersion: apps/v1
kind: Deployment
metadata:
  name: bybit-ai-alpha-agent
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bybit-bot
      component: alpha-agent
  template:
    metadata:
      labels:
        app: bybit-bot
        component: alpha-agent
    spec:
      containers:
        - name: alpha-agent
          image: us-central1-docker.pkg.dev/my-home-435112/unified-core-images/bybit-alpha@sha256:04fffacba0b16415f692b4b17db313aa7aafda6ef729ad11da5de4d325ff4879
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: bybit-bot-config
                  key: redis_url
            - name: BYBIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bybit-secrets
                  key: api-key
            - name: BYBIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: bybit-secrets
                  key: api-secret
