apiVersion: apps/v1
kind: Deployment
metadata:
  name: bybit-compliance
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bybit-compliance
  template:
    metadata:
      labels:
        app: bybit-compliance
    spec:
      containers:
        - name: compliance
          image: us-central1-docker.pkg.dev/my-home-435112/unified-core-images/bybit-compliance@sha256:dd976d6155f09f6c82744b0c17f563718ba64bcb79e65f23e004b19f9f21df73
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: bybit-bot-config
                  key: redis_url
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: bybit-bot-config
                  key: database_url
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
