apiVersion: apps/v1
kind: Deployment
metadata:
  name: bybit-compliance
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bybit-compliance
  template:
    metadata:
      labels:
        app: bybit-compliance
    spec:
      containers:
        - name: compliance
          image: us-central1-docker.pkg.dev/my-home-435112/unified-core-images/bybit-compliance@sha256:176371c1d8d05c7b48c27c5bea54d4f31f026486d7d69d827a4782b43f1f82a4
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: bybit-bot-config
                  key: redis_url
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: bybit-bot-config
                  key: database_url
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
