apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: us-central1-docker.pkg.dev/my-home-435112/unified-core-images/redis@sha256:eca6112ab727f397e5c982bf51137b8358599eb4e967dc0319401b0ab58f7512
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: trading
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescale
  template:
    metadata:
      labels:
        app: timescale
    spec:
      containers:
        - name: timescale
          image: us-central1-docker.pkg.dev/my-home-435112/unified-core-images/timescaledb@sha256:93c258f350576879bd0f344e1fc783181e8592c3e4cc69a277f4a480cb0e9232
          env:
            - name: POSTGRES_PASSWORD
              value: "trading_pass"
            - name: POSTGRES_USER
              value: "trading_user"
            - name: POSTGRES_DB
              value: "trading"
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: trading
spec:
  selector:
    app: timescale
  ports:
    - port: 5432
      targetPort: 5432
