apiVersion: apps/v1
kind: Deployment
metadata:
  name: bybit-ingestion
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bybit-ingestion
  template:
    metadata:
      labels:
        app: bybit-ingestion
    spec:
      containers:
        - name: ingestion
          image: us-central1-docker.pkg.dev/my-home-435112/unified-core-images/bybit-ingestion@sha256:4aad3833865106cf5f2363e79ea1b4c3127e5c468db24e71c966a23f0684a939
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: bybit-bot-config
                  key: redis_url
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
