apiVersion: apps/v1
kind: Deployment
metadata:
  name: bybit-risk-guard
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bybit-risk-guard
  template:
    metadata:
      labels:
        app: bybit-risk-guard
    spec:
      containers:
        - name: risk-guard
          image: us-central1-docker.pkg.dev/my-home-435112/unified-core-images/bybit-risk@sha256:19912d086047fad30a3cf2166b6f2b18d796f99fc2b4199f83e87de65fed1f5d
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: bybit-bot-config
                  key: redis_url
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
