import logging
import sys
from pathlib import Path

# Add project root to sys.path
sys.path.append(str(Path(__file__).parent.parent.parent.parent))

import torch
from TTS.api import TTS

from Projects.Content_Factory.src.lip_sync.live_portrait_controller import LivePortraitController
from Projects.Content_Factory.src.lip_sync.wav2lip_controller import Wav2LipController

# Note: XTTS client might be in Projects/AI_Core or similar
# For now, we will use a shell command or existing testing script logic for XTTS

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def generate_broadcast():
    # 1. Scripts/Topic
    text = "Приветствую! Это Unit-X с эксклюзивным выпуском новостей. Сегодня мы успешно запустили систему LivePortrait для создания гиперреалистичного контента. Будущее уже наступило."

    output_dir = Path("Projects/Content_Factory/outputs/production").resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    audio_path = output_dir / "news_audio.wav"
    # motion_path = output_dir / "unit_x_motion.mp4" # This is generated by LivePortrait, not a static path
    # final_path = output_dir / "final_news_broadcast.mp4" # This is generated by Wav2Lip, not a static path

    avatar_path = Path("Projects/Content_Factory/assets/avatars/unit_x.png").resolve()
    ref_wav = Path("secure_vault/biometrics/unit_x/ref.wav").resolve()

    # 2. Generate Audio (XTTS)
    logger.info("🎙️ Stage 1: Generating Audio with XTTS v2...")
    device = "mps" if torch.backends.mps.is_available() else "cpu"
    try:
        model_name = "tts_models/multilingual/multi-dataset/xtts_v2"
        tts = TTS(model_name).to(device)
        tts.tts_to_file(text=text, speaker_wav=str(ref_wav), language="ru", file_path=str(audio_path))
        logger.info(f"✅ Audio generated: {audio_path}")
    except Exception as e:
        logger.error(f"❌ Audio generation failed: {e}")
        return

    # 3. Generate Motion (LivePortrait)
    logger.info("🎬 Stage 2: Generating Head Motion (LivePortrait)...")
    lp_controller = LivePortraitController()
    lp_video = lp_controller.animate(str(avatar_path), output_filename="unit_x_motion.mp4")

    if not lp_video:
        logger.error("LivePortrait failed.")
        return

    # 4. Generate Lip-Sync (Wav2Lip)
    logger.info("👄 Stage 3: Applying Lip-Sync (Wav2Lip)...")
    w2l_controller = Wav2LipController()
    # We apply Wav2Lip ON TOP of the LivePortrait video
    final_video = w2l_controller.animate(
        face_path=str(lp_video), audio_path=str(audio_path), output_filename="final_news_broadcast.mp4"
    )

    if final_video:
        logger.info(f"✅ Final Production Success: {final_video}")
        return final_video


if __name__ == "__main__":
    generate_broadcast()
