import os
import sys
import threading
from pathlib import Path
import firebase_admin
from firebase_admin import credentials, firestore, storage
from dotenv import load_dotenv
import time

SRC_DIR = Path(__file__).parent.resolve()
load_dotenv(SRC_DIR / ".env", override=True)

print("🎧 Initializing Firebase Admin...")
cred = credentials.Certificate(str(SRC_DIR / "firebase-admin.json"))
firebase_admin.initialize_app(cred, {
    'storageBucket': 'unified-core-agent-db.firebasestorage.app'
})

db = firestore.client()
bucket = storage.bucket()

def process_job(doc_id, data):
    print(f"\n🚀 [Job {doc_id}] Processing triggered from Mobile App!")
    try:
        sys.path.insert(0, str(SRC_DIR))
        from src.pipeline.orchestrator_v4_advanced import run_advanced_pipeline
        
        # Parse data
        text = data.get("text", "Мотивационное видео про успех и технологии будущего.")
        scenes = data.get("scenes", [{"keyword": "futuristic technology cinematic"}, {"keyword": "success abstract cinematic"}])
        style = data.get("style", "impact")
        lang = data.get("lang", "ru")
        
        print(f"   [Job {doc_id}] Running Factory Pipeline...")
        # To avoid blocking the event loop or causing weird asyncio issues in some cases,
        # since run_advanced_pipeline is synchronous, we can just call it.
        final_video_path = run_advanced_pipeline(
            text=text, 
            lang=lang, 
            output_name=f"mobile_job_{doc_id}", 
            scenes=scenes, 
            style=style
        )
        
        if final_video_path and Path(final_video_path).exists():
            print(f"   [Job {doc_id}] Factory finished. Uploading to Firebase Storage...")
            blob_name = f"outputs/mobile_job_{doc_id}.mp4"
            blob = bucket.blob(blob_name)
            blob.upload_from_filename(str(final_video_path))
            blob.make_public()
            
            video_url = blob.public_url
            print(f"   [Job {doc_id}] Uploaded to: {video_url}")
            
            db.collection("factory_jobs").document(doc_id).update({
                "status": "ready",
                "video_url": video_url,
                "progress": 100
            })
            print(f"✅ [Job {doc_id}] Finished successfully!")
        else:
            raise Exception("Video generation failed (no output file returned).")
            
    except Exception as e:
        import traceback
        traceback.print_exc()
        db.collection("factory_jobs").document(doc_id).update({
            "status": "error",
            "error_msg": str(e)
        })
        print(f"❌ [Job {doc_id}] Failed with error: {e}")

def on_snapshot(col_snapshot, changes, read_time):
    for change in changes:
        if change.type.name == 'ADDED' or change.type.name == 'MODIFIED':
            data = change.document.to_dict()
            status = data.get("status")
            doc_id = change.document.id
            
            if status == "pending":
                print(f"🔔 Found pending job: {doc_id}")
                change.document.reference.update({"status": "processing", "progress": 10})
                t = threading.Thread(target=process_job, args=(doc_id, data))
                t.daemon = True
                t.start()
                
            elif status == "approved":
                print(f"📢 Job {doc_id} APPROVED for YouTube! Starting YouTube Upload...")
                change.document.reference.update({"status": "uploading_to_youtube"})
                # Launch youtube upload in background
                def upload_to_youtube(doc_id, data):
                    try:
                        # Assuming youtube upload logic
                        import subprocess
                        video_path = SRC_DIR / "outputs" / f"mobile_job_{doc_id}.mp4"
                        if not video_path.exists():
                            raise Exception("Local video file not found for upload.")
                        
                        cmd = [
                            sys.executable,
                            str(SRC_DIR / "src" / "uploaders" / "youtube_uploader.py"),
                            str(video_path),
                            data.get("title", "Generated by AI"),
                            data.get("description", "AI Video")
                        ]
                        subprocess.run(cmd, check=True)
                        
                        db.collection("factory_jobs").document(doc_id).update({
                            "status": "published"
                        })
                        print(f"✅ [Job {doc_id}] YouTube Publish Complete!")
                    except Exception as e:
                        print(f"❌ [Job {doc_id}] YouTube Publish Failed: {e}")
                        db.collection("factory_jobs").document(doc_id).update({
                            "status": "publish_error",
                            "error_msg": str(e)
                        })

                t = threading.Thread(target=upload_to_youtube, args=(doc_id, data))
                t.daemon = True
                t.start()

col_query = db.collection("factory_jobs")
watch = col_query.on_snapshot(on_snapshot)

print("======================================================")
print(" 🤖 SOVEREIGN FACTORY NODE (igor-gaming) IS ACTIVE")
print(" 📡 Listening for Firebase Mobile App commands...")
print("======================================================")

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    print("Shutting down listener...")
