# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x0c\x62ybit.bot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n\nMarketData\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08spot_ask\x18\x02 \x01(\x01\x12\x10\n\x08perp_bid\x18\x03 \x01(\x01\x12\x14\n\x0c\x66unding_rate\x18\x04 \x01(\x01\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"g\n\x06Signal\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08leverage\x18\x04 \x01(\x01\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\"y\n\x0eValidatedOrder\x12$\n\x06signal\x18\x01 \x01(\x0b\x32\x14.bybit.bot.v1.Signal\x12\x0f\n\x07risk_id\x18\x02 \x01(\t\x12\x30\n\x0cvalidated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xec\x01\n\x0f\x45xecutionReport\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\nasset_pair\x18\x02 \x01(\t\x12\x12\n\ntrade_side\x18\x03 \x01(\t\x12\x14\n\x0c\x65xecuted_qty\x18\x04 \x01(\x01\x12\x16\n\x0eprice_executed\x18\x05 \x01(\x01\x12\x16\n\x0e\x66mv_fiat_value\x18\x06 \x01(\x01\x12\x12\n\nfee_amount\x18\x07 \x01(\x01\x12\x14\n\x0c\x66\x65\x65_currency\x18\x08 \x01(\t\x12/\n\x0b\x65xecuted_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MARKETDATA']._serialized_start=66
  _globals['_MARKETDATA']._serialized_end=199
  _globals['_SIGNAL']._serialized_start=201
  _globals['_SIGNAL']._serialized_end=304
  _globals['_VALIDATEDORDER']._serialized_start=306
  _globals['_VALIDATEDORDER']._serialized_end=427
  _globals['_EXECUTIONREPORT']._serialized_start=430
  _globals['_EXECUTIONREPORT']._serialized_end=666
# @@protoc_insertion_point(module_scope)
