apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUliSzYzQjZ1THNCeUpuMXRPMDhINTh3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1lUSTFPR0l3TmpJdFl6QXlaaTAwWldReUxXRmpNVFV0TkRJME16WmpabUZsTjJSaApNQ0FYRFRJMk1ESXdPVEUwTURReE5sb1lEekl3TlRZd01qQXlNVFV3TkRFMldqQXZNUzB3S3dZRFZRUURFeVJoCk1qVTRZakEyTWkxak1ESm1MVFJsWkRJdFlXTXhOUzAwTWpRek5tTm1ZV1UzWkdFd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDY2N1VmFqN1owMGxFVXlEZnFSeVJaN2xGbHRKb2RvNHV2ZW9BUQpwTnRYTVNER2RPdnJvazVSUEJhOWRJUis3R2dsRUxLbjdQK0Q3bjVITENPaU0ycjdvMm93V2p1cTFVd0ZnMk5SCnM5NmRKWEwvd2xUWGpKNHFkR0p3Q2gvTmthMDVqYXREa2xPZU91TDZSTUo4djNPb2trMXhoQURkSDJSWU12TkQKc2NOaEM0VDBzWmIrblBYcGZHWHBpRFc0d2JvRWJGNDF6MFFRVm96aE8rcU04cVVSVjRkSEpGc2N1VXpEd2tpcwpxSWRxcWhuNFN6RFlaZUp4MTRJNURhZGZpZG94NmRnSHJwZWtkV2VUTm9jZ2VNY1JrVnZJNENLU1lNbTVHZjV4CllOSUZ4cCszV05PZXowTEtjaURMaW1aMWQxY0x0N2tpQk9TUys0T1ZhbzhkNC9neGFsWFptQUJUR25pNkprdXYKeW1XajlwSmhUbTZldTJZYlI1MVNKT0REK0cwL01EbmFCSE9JYnhRcUJPeHVyZGV0ZGdTMHpOdmhZV2dzOWVzSgpaNTdaV0V3QzRKcmxmOHA3NjZra2VZdlZoTHZNbnRBd1VZMk0xQnVCcnp2dzJMdXN6dXR6azNPZHZWWHM5Y05BCklwU3NEcUhRckhuZVhTZDN2dGgyRCtQUkxTVUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTnc1RmVJaHpQM2xuNEJvdEN1dVpKem0va0NxTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQVVPTis3NkJJOTF3T0VpQk1mSTdkMDhPUHJSU1FsTVNUSlVOWnBKWElLCkFiVEozMzc0NHcvY3o5bXF0VkExRHcyOEFLczJXekIvM1NxbmRISHRuN0Y3SlE1Qm9GL0FBOGJZazBCaFl0TkMKZnhiWUtVQ2pGUFBSdlFwVEEzNEFkQVpTaEZiMC9QWUJtMUMvREx6cm9UTXp3UlBLdzJXOEYyVmdzN0kwVHVsRApIM3NFYnpOQ1kxcEFOb21WdW8yUkFuZkUxQlgxcnFmVU1OejhIbmFqTGpRZDhxWWtvSlVtS3NUME5vVm9MeklZCkg2RTVHM2piTVZIVWhJYmF1Slk3ZWQwV0RPWDlmZ0dvRXRKUnhJK0lVQ2JkbHcrYmdiTVgvQVBsc3FIczg3VmQKR0p5TTJuR2RCeGJBdmFacFZVdzNSMzU2TzhtUnozSS9JZGxnY0dBT2g4K3oyV0hJZzZkWmpoTEt5VFpITTZIYQowaGtZc09BcFJab2djT3JqM0cwQmhULzVsdUZNNlMwOEVoNk9VNm1rbWZrL2djN1B4bjNxR2crRkt6UEU5cXU0CnRoN2lITTlUd1MrT3BNUEozVUxlL2NVY05HbFl2OUV6L0l2Vk1tYjZYKzdhOUJaRVJDbS9BbnJnT2F1MUkzc0sKc3BJRFkrWUxoczFUL0pEYmdQbENEZzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.45.138.169
  name: gke_my-home-435112_us-central1_autopilot-cluster-1
contexts:
- context:
    cluster: gke_my-home-435112_us-central1_autopilot-cluster-1
    user: gke_my-home-435112_us-central1_autopilot-cluster-1
  name: gke_my-home-435112_us-central1_autopilot-cluster-1
current-context: gke_my-home-435112_us-central1_autopilot-cluster-1
kind: Config
preferences: {}
users:
- name: gke_my-home-435112_us-central1_autopilot-cluster-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --use_application_default_credentials
      command: /opt/homebrew/share/google-cloud-sdk/bin/gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      provideClusterInfo: true
