apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment-gke.yaml
  - service.yaml

images:
  - name: ghcr.io/unified-system-core/unified_system_core/ai-telegram-bot
    newTag: 281a475


