apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-telegram-bot-sa
  namespace: trading
  annotations:
    iam.gke.io/gcp-service-account: telegram-bot-firestore@my-home-435112.iam.gserviceaccount.com
